export const AREAS = [
  { name: 'Gold Coast', slug: 'gold-coast', tagline: 'Full-service marketing across the entire Gold Coast region' },
  { name: 'Southport', slug: 'southport', tagline: 'Marketing services for the Gold Coast CBD and central business hub' },
  { name: 'Surfers Paradise', slug: 'surfers-paradise', tagline: 'Marketing for tourism, hospitality and retail businesses' },
  { name: 'Broadbeach', slug: 'broadbeach', tagline: 'Marketing for dining, events and lifestyle businesses' },
  { name: 'Burleigh Heads', slug: 'burleigh-heads', tagline: 'Marketing for boutique, wellness and creative businesses' },
  { name: 'Robina', slug: 'robina', tagline: 'Marketing for retail, professional services and health businesses' },
  { name: 'Nerang', slug: 'nerang', tagline: 'Marketing for trades, services and growing local businesses' },
  { name: 'Hope Island', slug: 'hope-island', tagline: 'Marketing for premium services, marina and golf course businesses' },
  { name: 'Paradise Point', slug: 'paradise-point', tagline: 'Marketing for waterfront and premium local businesses' },
  { name: 'Runaway Bay', slug: 'runaway-bay', tagline: 'Marketing for retail, trades and family-oriented businesses' },
  { name: 'Hollywell', slug: 'hollywell', tagline: 'Marketing for marine, trades and Broadwater businesses' },
  { name: 'Labrador', slug: 'labrador', tagline: 'Marketing for hospitality, trades and Broadwater businesses' },
  { name: 'Main Beach', slug: 'main-beach', tagline: 'Marketing for luxury hospitality and premium service businesses' },
  { name: 'Chevron Island', slug: 'chevron-island', tagline: 'Marketing for creative, hospitality and boutique businesses near HOTA' },
  { name: 'Isle of Capri', slug: 'isle-of-capri', tagline: 'Marketing for premium services near Capri on Via Roma' },
  { name: 'Mermaid Beach', slug: 'mermaid-beach', tagline: 'Marketing for luxury lifestyle and hospitality businesses' },
  { name: 'Nobby Beach', slug: 'nobby-beach', tagline: 'Marketing for hospitality, fitness and lifestyle businesses' },
  { name: 'Miami', slug: 'miami', tagline: 'Marketing for surf culture, lifestyle and hospitality businesses' },
  { name: 'Palm Beach', slug: 'palm-beach', tagline: 'Marketing for surf, lifestyle and growing coastal businesses' },
  { name: 'Currumbin', slug: 'currumbin', tagline: 'Marketing for tourism, community and coastal businesses' },
  { name: 'Tugun', slug: 'tugun', tagline: 'Marketing for airport corridor and coastal community businesses' },
  { name: 'Bilinga', slug: 'bilinga', tagline: 'Marketing for coastal accommodation and airport-adjacent businesses' },
  { name: 'Kirra', slug: 'kirra', tagline: 'Marketing for surf tourism and coastal hospitality businesses' },
  { name: 'Coolangatta', slug: 'coolangatta', tagline: 'Marketing for southern Gold Coast tourism and hospitality businesses' },
  { name: 'Advancetown', slug: 'advancetown', tagline: 'Marketing for Advancetown local businesses and services' },
  { name: 'Alberton', slug: 'alberton', tagline: 'Marketing for Alberton local businesses and services' },
  { name: 'Arundel', slug: 'arundel', tagline: 'Marketing for Arundel local businesses and services' },
  { name: 'Ashmore', slug: 'ashmore', tagline: 'Marketing for Ashmore local businesses and services' },
  { name: 'Austinville', slug: 'austinville', tagline: 'Marketing for Austinville local businesses and services' },
  { name: 'Benowa', slug: 'benowa', tagline: 'Marketing for Benowa local businesses and services' },
  { name: 'Biggera Waters', slug: 'biggera-waters', tagline: 'Marketing for Biggera Waters local businesses and services' },
  { name: 'Bonogin', slug: 'bonogin', tagline: 'Marketing for Bonogin local businesses and services' },
  { name: 'Broadbeach Waters', slug: 'broadbeach-waters', tagline: 'Marketing for Broadbeach Waters local businesses and services' },
  { name: 'Bundall', slug: 'bundall', tagline: 'Marketing for Bundall local businesses and services' },
  { name: 'Burleigh Waters', slug: 'burleigh-waters', tagline: 'Marketing for Burleigh Waters local businesses and services' },
  { name: 'Carrara', slug: 'carrara', tagline: 'Marketing for Carrara local businesses and services' },
  { name: 'Cedar Creek', slug: 'cedar-creek', tagline: 'Marketing for Cedar Creek local businesses and services' },
  { name: 'Clagiraba', slug: 'clagiraba', tagline: 'Marketing for Clagiraba local businesses and services' },
  { name: 'Clear Island Waters', slug: 'clear-island-waters', tagline: 'Marketing for Clear Island Waters local businesses and services' },
  { name: 'Coombabah', slug: 'coombabah', tagline: 'Marketing for Coombabah local businesses and services' },
  { name: 'Coomera', slug: 'coomera', tagline: 'Marketing for Coomera local businesses and services' },
  { name: 'Currumbin Valley', slug: 'currumbin-valley', tagline: 'Marketing for Currumbin Valley local businesses and services' },
  { name: 'Currumbin Waters', slug: 'currumbin-waters', tagline: 'Marketing for Currumbin Waters local businesses and services' },
  { name: 'Elanora', slug: 'elanora', tagline: 'Marketing for Elanora local businesses and services' },
  { name: 'Gaven', slug: 'gaven', tagline: 'Marketing for Gaven local businesses and services' },
  { name: 'Gilberton', slug: 'gilberton', tagline: 'Marketing for Gilberton local businesses and services' },
  { name: 'Gilston', slug: 'gilston', tagline: 'Marketing for Gilston local businesses and services' },
  { name: 'Guanaba', slug: 'guanaba', tagline: 'Marketing for Guanaba local businesses and services' },
  { name: 'Helensvale', slug: 'helensvale', tagline: 'Marketing for Helensvale local businesses and services' },
  { name: 'Highland Park', slug: 'highland-park', tagline: 'Marketing for Highland Park local businesses and services' },
  { name: 'Jacobs Well', slug: 'jacobs-well', tagline: 'Marketing for Jacobs Well local businesses and services' },
  { name: 'Kingsholme', slug: 'kingsholme', tagline: 'Marketing for Kingsholme local businesses and services' },
  { name: 'Lower Beechmont', slug: 'lower-beechmont', tagline: 'Marketing for Lower Beechmont local businesses and services' },
  { name: 'Luscombe', slug: 'luscombe', tagline: 'Marketing for Luscombe local businesses and services' },
  { name: 'Maudsland', slug: 'maudsland', tagline: 'Marketing for Maudsland local businesses and services' },
  { name: 'Mermaid Waters', slug: 'mermaid-waters', tagline: 'Marketing for Mermaid Waters local businesses and services' },
  { name: 'Merrimac', slug: 'merrimac', tagline: 'Marketing for Merrimac local businesses and services' },
  { name: 'Molendinar', slug: 'molendinar', tagline: 'Marketing for Molendinar local businesses and services' },
  { name: 'Mount Nathan', slug: 'mount-nathan', tagline: 'Marketing for Mount Nathan local businesses and services' },
  { name: 'Mudgeeraba', slug: 'mudgeeraba', tagline: 'Marketing for Mudgeeraba local businesses and services' },
  { name: 'Natural Bridge', slug: 'natural-bridge', tagline: 'Marketing for Natural Bridge local businesses and services' },
  { name: 'Neranwood', slug: 'neranwood', tagline: 'Marketing for Neranwood local businesses and services' },
  { name: 'Norwell', slug: 'norwell', tagline: 'Marketing for Norwell local businesses and services' },
  { name: 'Numinbah Valley', slug: 'numinbah-valley', tagline: 'Marketing for Numinbah Valley local businesses and services' },
  { name: 'Ormeau', slug: 'ormeau', tagline: 'Marketing for Ormeau local businesses and services' },
  { name: 'Ormeau Hills', slug: 'ormeau-hills', tagline: 'Marketing for Ormeau Hills local businesses and services' },
  { name: 'Oxenford', slug: 'oxenford', tagline: 'Marketing for Oxenford local businesses and services' },
  { name: 'Pacific Pines', slug: 'pacific-pines', tagline: 'Marketing for Pacific Pines local businesses and services' },
  { name: 'Parkwood', slug: 'parkwood', tagline: 'Marketing for Parkwood local businesses and services' },
  { name: 'Pimpama', slug: 'pimpama', tagline: 'Marketing for Pimpama local businesses and services' },
  { name: 'Reedy Creek', slug: 'reedy-creek', tagline: 'Marketing for Reedy Creek local businesses and services' },
  { name: 'South Stradbroke Island', slug: 'south-stradbroke-island', tagline: 'Marketing for South Stradbroke Island local businesses and services' },
  { name: 'Southern Moreton Bay Islands', slug: 'southern-moreton-bay-islands', tagline: 'Marketing for Southern Moreton Bay Islands local businesses and services' },
  { name: 'Springbrook', slug: 'springbrook', tagline: 'Marketing for Springbrook local businesses and services' },
  { name: 'Stapylton', slug: 'stapylton', tagline: 'Marketing for Stapylton local businesses and services' },
  { name: 'Steiglitz', slug: 'steiglitz', tagline: 'Marketing for Steiglitz local businesses and services' },
  { name: 'Tallai', slug: 'tallai', tagline: 'Marketing for Tallai local businesses and services' },
  { name: 'Tallebudgera', slug: 'tallebudgera', tagline: 'Marketing for Tallebudgera local businesses and services' },
  { name: 'Tallebudgera Valley', slug: 'tallebudgera-valley', tagline: 'Marketing for Tallebudgera Valley local businesses and services' },
  { name: 'Upper Coomera', slug: 'upper-coomera', tagline: 'Marketing for Upper Coomera local businesses and services' },
  { name: 'Varsity Lakes', slug: 'varsity-lakes', tagline: 'Marketing for Varsity Lakes local businesses and services' },
  { name: 'Willow Vale', slug: 'willow-vale', tagline: 'Marketing for Willow Vale local businesses and services' },
  { name: 'Wongawallan', slug: 'wongawallan', tagline: 'Marketing for Wongawallan local businesses and services' },
  { name: 'Woongoolba', slug: 'woongoolba', tagline: 'Marketing for Woongoolba local businesses and services' },
  { name: 'Worongary', slug: 'worongary', tagline: 'Marketing for Worongary local businesses and services' },
  { name: 'Yatala', slug: 'yatala', tagline: 'Marketing for Yatala local businesses and services' },
  { name: 'Brisbane', slug: 'brisbane', tagline: 'Extending Gold Coast marketing expertise to SEQ capital' },
  { name: 'South East Queensland', slug: 'south-east-queensland', tagline: 'Regional marketing coverage across the SEQ corridor' },
] as const;

export const TOP_5_AREAS = [
  { name: 'Southport', slug: 'southport' },
  { name: 'Surfers Paradise', slug: 'surfers-paradise' },
  { name: 'Broadbeach', slug: 'broadbeach' },
  { name: 'Burleigh Heads', slug: 'burleigh-heads' },
  { name: 'Robina', slug: 'robina' },
] as const;

export const SERVICE_LINKS = [
  { href: '/seo-gold-coast', label: 'SEO' },
  { href: '/google-ads-gold-coast', label: 'Google Ads' },
  { href: '/email-marketing-gold-coast', label: 'Email Marketing' },
  { href: '/lead-generation-gold-coast', label: 'Lead Generation' },
  { href: '/digital-marketing-gold-coast', label: 'Digital Marketing' },
  { href: '/marketing-automation-gold-coast', label: 'Marketing Automation' },
] as const;
